# 01 - Carga y Limpieza de Datos
## Sistema de Recomendación de Películas basado en Letterboxd

In [1]:
import pandas as pd
import numpy as np
import os
from dotenv import load_dotenv

In [2]:
load_dotenv('../.env')
TMDB_API_KEY = os.getenv('TMDB_API_KEY')
print("API Key cargada:", "Sí" if TMDB_API_KEY else "No")

API Key cargada: Sí

### 1.1 Cargar el archivo CSV de Letterboxd

In [3]:
df = pd.read_csv('../data/raw/ratings.csv')
print(f"Total de películas calificadas: {len(df)}")
print(f"\nColumnas: {df.columns.tolist()}")
df.head(10)

Total de películas calificadas: 193

Columnas: ['Date', 'Name', 'Year', 'Letterboxd URI', 'Rating']

,Date,Name,Year,Letterboxd URI,Rating
0,2026-04-10,The Marvels,2023,https://boxd.it/mwU4,1.5
1,2026-04-10,Spider-Man,2002,https://boxd.it/2a8i,3.5
2,2026-04-10,Spider-Man 3,2007,https://boxd.it/2a7Y,2.5
3,2026-04-10,Spider-Man 2,2004,https://boxd.it/2a88,4.5
4,2026-04-10,Spider-Man: Into the Spider-Verse,2018,https://boxd.it/azpY,4.5
5,2026-04-10,Spider-Man: Across the Spider-Verse,2023,https://boxd.it/kSz4,4.5
6,2026-04-10,Spider-Man: No Way Home,2021,https://boxd.it/nwRw,3.5
7,2026-04-10,Spider-Man: Homecoming,2017,https://boxd.it/aboM,1.5
8,2026-04-10,Spider-Man: Far From Home,2019,https://boxd.it/fegG,1.5
9,2026-04-10,The Amazing Spider-Man 2,2014,https://boxd.it/3utM,4.5

### 1.2 Exploración inicial

In [4]:
print("Forma del DataFrame:", df.shape)
print("\nTipos de datos:")
print(df.dtypes)
print("\nEstadísticas de calificaciones:")
print(df['Rating'].describe())
print("\nDistribución de calificaciones:")
print(df['Rating'].value_counts().sort_index())

Forma del DataFrame: (193, 5)

Tipos de datos:
Date                  str
Name                  str
Year                int64
Letterboxd URI        str
Rating            float64
dtype: object

Estadísticas de calificaciones:
count    193.000000
mean       2.598446
std        0.995117
min        0.500000
25%        2.000000
50%        2.500000
75%        3.000000
max        5.000000
Name: Rating, dtype: float64

Distribución de calificaciones:
Rating
0.5    10
1.0     4
1.5    24
2.0    30
2.5    41
3.0    37
3.5    24
4.0    13
4.5     6
5.0     4
Name: count, dtype: int64

### 1.3 Limpieza de datos
Renombramos columnas y eliminamos filas sin calificación.

In [5]:
df_clean = df.rename(columns={
    'Name': 'title',
    'Year': 'year',
    'Rating': 'my_score',
    'Letterboxd URI': 'letterboxd_url',
    'Date': 'date_rated'
})

df_clean = df_clean[df_clean['my_score'] > 0].copy()
df_clean.reset_index(drop=True, inplace=True)
print(f"Películas calificadas (score > 0): {len(df_clean)}")
df_clean.head(10)

Películas calificadas (score > 0): 193

,date_rated,title,year,letterboxd_url,my_score
0,2026-04-10,The Marvels,2023,https://boxd.it/mwU4,1.5
1,2026-04-10,Spider-Man,2002,https://boxd.it/2a8i,3.5
2,2026-04-10,Spider-Man 3,2007,https://boxd.it/2a7Y,2.5
3,2026-04-10,Spider-Man 2,2004,https://boxd.it/2a88,4.5
4,2026-04-10,Spider-Man: Into the Spider-Verse,2018,https://boxd.it/azpY,4.5
5,2026-04-10,Spider-Man: Across the Spider-Verse,2023,https://boxd.it/kSz4,4.5
6,2026-04-10,Spider-Man: No Way Home,2021,https://boxd.it/nwRw,3.5
7,2026-04-10,Spider-Man: Homecoming,2017,https://boxd.it/aboM,1.5
8,2026-04-10,Spider-Man: Far From Home,2019,https://boxd.it/fegG,1.5
9,2026-04-10,The Amazing Spider-Man 2,2014,https://boxd.it/3utM,4.5

### 1.4 Exportar datos limpios

In [6]:
df_clean.to_csv('../data/processed/movies_clean.csv', index=False)
print("CSV guardado en data/processed/movies_clean.csv")

CSV guardado en data/processed/movies_clean.csv